ced091/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.main, name="main"),
    path('station/', include('station_meteo.urls')),
    path('libeiki/', include('libeiki.urls')),
    path('document/', include('docs.urls')),
    path('pokelira/', include('pokelira.urls')),
    path('sign-up/', views.signup, name="signup"),
    path('memo/', include('memo.urls')),
    path('admin/', admin.site.urls),
]

docs/urls.py
from django.urls import path, include
from . import views

app_name='docs'

urlpatterns = [
    path('documentation/<path:path>', views.main, name="main"),
]

libeiki/urls.py
from django.urls import path

from . import views

app_name = 'libeiki'

urlpatterns = [
    path('', views.accueil, name='accueil'),
    path('reiki/', views.reiki, name='reiki'),
    path('quisuisje/', views.quisuisje, name='quisuisje'),
    path('massage/', views.massage, name='massage'),
    path('sophrologie/', views.sophrologie, name='sophrologie'),
    path('numerologie/', views.numerologie, name='numerologie'),
    path('lignee-reiki/', views.lignee_reiki, name="lignee_reiki"),
    path('contact/', views.contact, name='contact'),
    path('tarif-reiki/', views.tarif_reiki, name='tarif_reiki'),
    path('tarif-numerologie/', views.tarif_numerologie, name='tarif_numerologie'),
    path('tarif-massage/', views.tarif_massage,name='tarif_massage'),
    path('tarif-sophrologie/', views.tarif_sophrologie,name='tarif_sophrologie'),
    path('send-commentaire/', views.send_commentaire, name='send_commentaire'),
    path('mentions-legales/', views.mentions_legales, name='mentions_legales'),
]

libeiki/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Commentaire(models.Model):
    pseudo = models.CharField(max_length=50)
    note = models.IntegerField()
    texte = models.TextField()
    date_com = models.DateField(default=timezone.now)
    visible = models.BooleanField(default=False)

    def __str__(self):
        return "Com' de " + str(self.pseudo)
    
    class Meta:
        ordering = ['-date_com']

libeiki/forms.py
# forms.py
from django import forms
from .models import Commentaire

class StarRatingWidget(forms.Widget):
    template_name = 'libeiki/stars.html'

    def format_value(self, value):
        return str(value)

class CommentaireForm(forms.ModelForm):
    class Meta:
        model = Commentaire
        fields = ['pseudo', 'note', 'texte']

libeiki/views.py
import logging

from django.shortcuts import render, redirect
from .forms import CommentaireForm
from django.core.mail import EmailMessage
from django.utils import timezone

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Commentaire

logger = logging.getLogger(__name__)

def log_user(request, vue):
    username = request.user.username if request.user.is_authenticated else 'Anonymous'
    current_datetime = timezone.now().strftime("%Y-%m-%d %H:%M:%S")
    ip_address = request.META.get('HTTP_X_FORWARDED_FOR', None)
    if ip_address is None:
        # Si l'en-tête X-Forwarded-For n'est pas disponible, utilisez l'adresse IP par défaut
        ip_address = request.META.get('REMOTE_ADDR', 'unknown')
    else:
        # Séparez les adresses IP si X-Forwarded-For contient plusieurs adresses
        ip_address = ip_address.split(",")[0].strip()
    logger.info(f'[{current_datetime}][{username}][{ip_address}] Accès à la vue {vue}')

# def envoyer_email_apres_soumission(commentaire, **kwargs):
#     message = f"Un nouveau commentaire a été soumis le {commentaire.date_com}.\n Voici son contenu : {commentaire.texte}. \n Sa note  : {commentaire.note}. \n Le pseudo : {commentaire.pseudo} \n Vous pouvez le rendre visible sur le site en cochant la case 'visible' dans le mode admin de votre site/admin.\n Tchuss."
#     email_msg = EmailMessage(
#         subject='Nouvelle soumission de commentaire LIBEIKI', 
#         body=message, 
#         from_email='ikiebil92@hotmail.com',
#         to=["ced091@hotmail.fr",  "libellule_1982@hotmail.com"]
#     )
#     email_msg.send()

def accueil(request):
    log_user(request, "accueil/libeiki")
    commentaires = Commentaire.objects.filter(visible=True)

    # Définissez le nombre d'éléments par page
    elements_par_page = 5

    # Initialisez l'objet Paginator avec la liste des commentaires et le nombre d'éléments par page
    paginator = Paginator(commentaires, elements_par_page)

    # Obtenez le numéro de la page à partir des paramètres de requête
    page = request.GET.get('page')
    try:
        # Obtenez les commentaires pour la page spécifiée
        commentaires_page = paginator.page(page)
    except PageNotAnInteger:
        # Si la page n'est pas un entier, affichez la première page
        commentaires_page = paginator.page(1)
    except EmptyPage:
        # Si la page est hors de portée (par exemple, 9999), affichez la dernière page
        commentaires_page = paginator.page(paginator.num_pages)
    context = {
        "commentaires": commentaires_page
    }
    return render(request, "libeiki/accueil.html", context)

def reiki(request):
    log_user(request, "reiki")
    return render(request, "libeiki/reiki.html")

def numerologie(request):
    log_user(request, "numerologie")
    return render(request, "libeiki/numerologie.html")

def quisuisje(request):
    log_user(request, "quisuisje")
    return render(request, "libeiki/quisuisje.html")

def massage(request):
    log_user(request, "massage")
    return render(request, "libeiki/massage.html")

def sophrologie(request):
    log_user(request, "sophrologie")
    return render(request, "libeiki/sophrologie.html")

def lignee_reiki(request):
    log_user(request, "lignee_reiki")
    return render(request, "libeiki/lignee-reiki.html")

def contact(request):
    log_user(request, "contact")
    return render(request, "libeiki/contact.html")

def tarif_reiki(request):
    log_user(request, "tarif_reiki")
    return render(request, "libeiki/tarif-reiki.html")

def tarif_numerologie(request):
    log_user(request, "tarif_numerologie")
    return render(request, "libeiki/tarif-numerologie.html")

def tarif_massage(request):
    log_user(request, "tarif_massage")
    return render(request, "libeiki/tarif-massage.html")

def tarif_sophrologie(request):
    log_user(request, "tarif_sophrologie")
    return render(request, "libeiki/tarif-sophrologie.html")

def generer_star_rating(value):
    return [
        {
            'index': x,
            'active': x <= value,
            'value': x / 2,
            'checked': x / 2 == value,
        }
        for x in range(1, 11)
    ]

def send_commentaire(request):
    
    log_user(request, "send_commentaire")
    if request.POST:
        form = CommentaireForm(request.POST)
        if form.is_valid():
            comm = form.save()
            print("merci pour votre contribution")
            # envoyer_email_apres_soumission(comm)
            return redirect('libeiki:accueil')
        else:
            print(f"erreurs suivantes : {form.errors}  ")
    else:
        form = CommentaireForm()
            
    context ={
        'form': form,
        'star_data': 5,
    }
    return render(request, "libeiki/commentaire.html", context)

def mentions_legales(request):
    return render(request, "libeiki/mentions_legales.html")

libeiki/templates/libeiki/accueil.html
{% extends "libeiki/base.html" %}

{% load static %}

{% load custom_tags %}

{% block menu %}
    {% include 'libeiki/menu.html' %}
{% endblock %}

{% block content %}
<style>
.orbit-image {
    background-color: #76B39B;
    
}

.contenu-principal {
    padding: 20px;
}

.thumbnail {
    border: none;
}

.in_orbit {            
    color: white;
    text-align: center;
    padding: 0px;
}

.orbit-container, .orbit-image {
    width: 100%;
    height: 100%;
    object-fit: cover;
    position: relative;
}

.orbit-container {
    padding:0px;
}

.custom-text-container {
    position: absolute;
    top: 80%;
    left: 20%;
    transform: translate(-50%, -50%);
    text-align: center;
    color: black; 
    font-size: 24px;
}

.custom-text-container a {
    color: black; 
    background-color: rgba(0, 0, 0, 0);
    font-size: 40px;
    border: 3px solid black;
    padding: 15px;
} 

.orbit-previous, .orbit-next {
    margin-top: 20px;
    color: black;
}

.pagination {
  display: flex;
  align-items: center;
  justify-content: center;
}

.step-links {
  display: flex;
  align-items: center;
  justify-content: center;
}

.current {
  margin: 0 10px;
}

.star {
    width: 30px;
    height: 30px;
    cursor: pointer;
    margin-right: 5px;
    position: relative;
    display: flex;
    justify-content: center;
    align-items: center;
    border: 0px solid black;
    border-radius: 50%;
    box-sizing: border-box;
  }

.star::before {
  content: '\2605';
  font-size: 30px;
  color: #d4af37;
}

.star-container {
  display: flex;
  align-items: center;
}

#a_nav {
  color: black;
}

.callout {
  display: flex;
  flex-direction: column;
  align-items: center;
  overflow: auto;
}

@media only screen and (max-width: 768px) {
  .custom-text-container {
      position: absolute;
      top: 80%;
      left: 20%;
      transform: translate(-50%, -50%);
      text-align: center;
      color: black; 
      font-size: 16px;
  }

  .custom-text-container a {
      color: black; 
      background-color: rgba(0, 0, 0, 0);
      font-size: 18px;
      border: 1px solid black;
      padding: 15px;
  } 

  .orbit-container .orbit-image, .orbit {
    height: 40vh; /* Réglez la hauteur selon vos préférences */
  }

}
</style>
<body>
  <div class="contenu-principal">               
    <div class="orbit" role="region" aria-label="Favorite Space Pictures" data-orbit>
      <div class="orbit-wrapper">
        <div class="orbit-controls">
          <button class="orbit-previous"><span class="show-for-sr">Previous Slide</span>&#9664;&#xFE0E;</button>
          <button class="orbit-next"><span class="show-for-sr">Next Slide</span>&#9654;&#xFE0E;</button>
        </div>
        <ul class="orbit-container">
          <li class="is-active orbit-slide">
            <figure class="orbit-figure">
              <img class="orbit-image" src="{% static '/photos/reiki.jpg' %}" alt="Reiki" class="image-redimensionnee">
              <div class="custom-text-container">
                  <br>
                  <br>
                  <a href="#">JE RESERVE</a>
              </div>
            </figure>
          </li>
          <li class="orbit-slide">
            <figure class="orbit-figure">
              <img class="orbit-image" src="{% static '/photos/sophro.jpg' %}" alt="Sophrologie" class="image-redimensionnee">
              <div class="custom-text-container">
                  <br>
                  <br>
                  <a href="#">JE COMMANDE</a>
              </div>
            </figure>
          </li>
          <li class="orbit-slide">
            <figure class="orbit-figure">
              <img class="orbit-image" src="{% static '/photos/massage.jpg' %}" alt="Massage tête" class="image-redimensionnee">
              <div class="custom-text-container">
                  <br>
                  <br>
                  <a href="#">JE RESERVE</a>
              </div>
            </figure>
          </li>
          <li class="orbit-slide">
            <figure class="orbit-figure">
              <img class="orbit-image" src="{% static '/photos/numerologie.jpg' %}" alt="Sophrologie" class="image-redimensionnee">
              <div class="custom-text-container">
                  <br>
                  <br>
                  <a href="#">JE RESERVE</a>
              </div>
            </figure>
          </li>          
        </ul>
      </div>             
    </div>
    <div class="grid-container intro">   
      <fieldset class="fieldset">        
        <legend>Présentation</legend>         
      <p class="intro">Plongez dans un monde dédié à votre épanouissement, où le Reiki apaise, la sophrologie équilibre, 
        les massages baguette Kansa réconfortent, et les études de numérologie éclairent votre chemin. Cette expérience unique, 
        façonnée selon vos besoins, vous offre le bien-être dans le confort de votre domicile, 
        où chaque aspect de votre vie prend vie de manière harmonieuse.
      </p>
    </fieldset>
    </div>
    {% if commentaires %}
    <div class="grid-container commentaire" style="background-color: transparent; padding-top: 50px;">

      <fieldset class="fieldset large-12 cell">
        <legend>Ils nous racontent leur expérience chez LIBEIKI</legend>
        {% for commentaire in commentaires %} 
        <div class="callout" id="commentaire{{ commentaire.id }}" style="background-color: transparent; width:70%; margin: auto; margin-bottom: 30px; border-color:#54977C;">              
          <div style="font-weight: bold; font-size: 25px; color:#54977C;">
            {{ commentaire.pseudo}}
          </div>
          <div style="font-style: italic; font-size: 20px;">
            '' {{ commentaire.texte|linebreaksbr }} ''
          </div>
          <div>
            <p>
              <div class="star-container">
                {% for i in commentaire.note|get_range %}
                  <div class="star"></div>
                {% endfor %}
                </div>
          </p>
          </div>  
          <div class="date_com">
            le {{ commentaire.date_com }}
          </div>        
        </div>
        {% endfor %}
        <div class="pagination">
          <span class="step-links">
            {% if commentaires.has_previous %}
              <a id="a_nav" href="?page=1#comments-section">&laquo; premier</a>
              <a id="a_nav" href="?page={{ commentaires.previous_page_number }}#comments-section">précédant</a>
            {% endif %}
        
            <span class="current">
              Page {{ commentaires.number }} de {{ commentaires.paginator.num_pages }}.
            </span>
        
            {% if commentaires.has_next %}
              <a id="a_nav" href="?page={{ commentaires.next_page_number }}#comments-section">suivant</a>
              <a id="a_nav"href="?page={{ commentaires.paginator.num_pages }}#comments-section">dernier &raquo;</a>
            {% endif %}
          </span>
        </div>
      </fieldset>
    </div>
    {% endif %}
  </div>
</body>
<script>

  document.addEventListener('DOMContentLoaded', function() {
    function scrollToComments() {
      const commentsSection = document.getElementById('comments-section');
      if (commentsSection) {
        commentsSection.scrollIntoView({ behavior: 'smooth' });
      }
    }
    const paginationLinks = document.querySelectorAll('.pagination a');
    paginationLinks.forEach(function(link) {
      link.addEventListener('click', scrollToComments);
    });
  });
</script>

<footer>
{% include 'libeiki/footer.html' %}
<footer>
{% endblock %}

libeiki/templates/libeiki/commentaire.html
{% extends "libeiki/base.html" %}

{% load static %}

{% block menu %}
    {% include 'libeiki/menu.html' %}
{% endblock %}

{% block content %}



<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<style>
    .button.secondary{
        text-align: center;
        background-color: black;
    }
    .titre {
        font-size: 28px;
    }
    .star-rating {
        font-size: 24px;
        color: #ddd;
    }

    .star-rating .star {
        cursor: pointer;
    }

    .star-rating .active {
        color: #ffcc00;
    }
   
    .formulaire {
      display: flex;
      flex-direction: column;
      align-items: center;
    }

    .star-container {
      display: flex;
    }

    .star {
      width: 30px;
      height: 30px;
      cursor: pointer;
      margin-right: 5px; /* Espacement entre les étoiles (modifiable) */
      position: relative;
      display: flex;
      justify-content: center;
      align-items: center;
      border: 1px solid black; /* Bordure noire de 1 pixel */
      border-radius: 50%; /* Utilisez la bordure arrondie pour obtenir une forme d'étoile */
      box-sizing: border-box; /* Inclure la bordure dans la largeur et la hauteur */
    }

    .star::before {
      content: '\2605'; /* Caractère d'étoile Unicode */
      font-size: 30px; /* Taille de la police de l'étoile */
      color: white; /* Couleur de l'étoile */
    }

    .star.clicked::before {
      color: #d4af37; /* Couleur de l'étoile jaune plus sombre au clic */
    }

    .star.transparent::before {
      color: transparent !important; /* Rend l'étoile transparente */
      border: 1px solid transparent !important; /* Rend la bordure transparente */
    }

    #yellowCount {
      margin-top: 20px; /* Ajustez la marge pour déplacer le texte plus bas */
    }
  </style>
  

  

  <script>
    document.addEventListener('DOMContentLoaded', function() {
    // Récupère l'élément input par son ID
    var champNote = document.getElementById('id_note');

    // Rend le champ invisible en modifiant la propriété CSS
    champNote.style.visibility = 'hidden';
});
    function changeColor(element) {
      // Récupère toutes les étoiles dans le même conteneur
      var stars = document.querySelectorAll('.star');

      // Récupère l'index de l'étoile cliquée
      var clickedIndex = Array.from(stars).indexOf(element);

      // Parcours les étoiles et applique la couleur jaune aux étoiles à gauche
      for (var i = 0; i <= clickedIndex; i++) {
        stars[i].classList.add('clicked');
        stars[i].classList.remove('transparent');
      }

      // Parcours les étoiles et rend les étoiles à droite transparentes
      for (var i = clickedIndex + 1; i < stars.length; i++) {
        stars[i].classList.add('transparent');
        stars[i].classList.remove('clicked');
      }

      // Met à jour le nombre d'étoiles jaunes affiché
      updateYellowCount();
    }

    function updateYellowCount() {
      var yellowStars = document.querySelectorAll('.star.clicked');
      document.getElementById('id_note').innerText = yellowStars.length;
      // Récupère l'élément input par son ID
        var champNote = document.getElementById('id_note');

        // Définit la valeur du champ
        champNote.value = yellowStars.length;
    }
  </script>

<div class="grid-container">
    <div class="grid-x formulaire">
        <form method="post" action="{% url 'libeiki:send_commentaire' %}">
            {% csrf_token %}
            <div><p><span class="titre">Pseudo :</span> {{ form.pseudo }}</p></div>
            <div>
            <p><span class="titre">note :</span>
                <div class="star-container">
                    <div class="star" onclick="changeColor(this)"></div>
                    <div class="star" onclick="changeColor(this)"></div>
                    <div class="star" onclick="changeColor(this)"></div>
                    <div class="star" onclick="changeColor(this)"></div>
                    <div class="star" onclick="changeColor(this)"></div>
                  </div>
            </p>
            </div><p>{{ form.note }}</p> 
            
            <div><p><span class="titre">Commentaire : </span>{{ form.texte }}</p></div>
            
            <button class="button secondary" type="submit">Soumettre</button>
        </form>
    </div>
</div>

<footer>
  {% include 'libeiki/footer.html' %}
</footer>
{% endblock %}

libeiki/templates/libeiki/menu.html
{% extends "libeiki/base.html" %}

{% load static %}

{% block menu %}

<style>
  @font-face {
    font-family: "Simsun";
    src: url("https://fontsforyou.com/fonts/s/Simsun.ttf");
  }
    /* Style pour le texte au-dessus des icônes sociales */
  .social-icons-container, .menu-container {
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  .social-text {
    margin-bottom: 10px;
    color: white;
    font-size: 16px;
  }

  .title {
    color:white;
    margin-top: -30px; 
    text-align: center;
  }

  h3 {
    font-family: "SimSun";
  }
  nav {
    background-image: url('{% static "/photos/fond.png" %}');
        background-size: cover;
        background-position: center;
    color: #fff;
    padding: 10px;
    display: flex;
    align-items: center;
    justify-content: space-between;
  }

  .menu-ul {
    list-style: none;
    margin: 0;
    padding: 0;
    display: flex;
  }

  .menu-li {
    margin-right: 20px;
    position: relative;
  }

  a {
    text-decoration: none;
    color: white;
    font-weight: bold;
  }

  .logo-container {
    display: flex;
    align-items: center;
  }

  .logo {
    max-width: 150px;
    height: auto;
    padding-left: 0px;
  }

  figcaption {
    text-align: center; 
    color: white;
  }

  #nom {
    margin: 0;
    color: white;
  }

  .dropdown {
    position: absolute;
    top: 100%;
    left: -20px;
    display: none;
    background-color: #588573;
    padding: 10px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    white-space: nowrap;
    z-index: 2;
  }

  .dropdown a {
    color: white;
    display: block;
    z-index: 2;
  }

  .dropdown {
    z-index: 10;
  }

  /* Nouvelle classe pour aligner les éléments à droite */
  .social-icons {
    display: flex;
    align-items: center;
  }

  .social-icons, .social {
    margin-right: 10px;
    z-index: 11;
  }

  /* Style pour le bouton de menu sur les écrans plus petits */
  .menu-icon {.social-text {
    margin-bottom: 10px; /* Ajustez cette valeur selon vos besoins */
    color: white; /* Choisissez la couleur du texte */
    font-size: 16px; /* Choisissez la taille de police */
  }
    display: none;
    cursor: pointer;
  }

  a:hover {
    border-bottom: 2px solid #fff;
    color: white; /* Changez cette valeur pour définir la nouvelle couleur au survol */
  }

  a:visited {
  color: white; /* Couleur des liens visités */
  }

  .contenu-principal.menu-open {
    margin-top: 155px; /* Ajustez la valeur selon la hauteur du sous-menu */
    transition: margin-top 0.3s ease-out;
  }

  .active_sub {
      display: flex;
      flex-direction: column;
      margin-top: 0px;
      position: absolute;
      left: 0;
      background-color: #345D4D;
      z-index: 2;
    }

    .social {
      font-size: 30px;
      margin: 10px;
    }
     
  @media only screen and (max-width: 1260px) {

    .social-text {
      font-size: 12px; /* Choisissez la taille de police */
    }

    #all-menu {
      text-align: center;
    }

    .logo {
      margin-right: 0;
      order: -1;
      width: 120px;
      margin-left: -20px;
    }

    .dropdown-max {
      display: none;
      background-image: url('{% static "/photos/fond.png" %}');
        background-size: cover;
        background-position: center;
    }

    ul.dropdown {
      width: 100%;
      flex-direction: column;
      position: relative;
      z-index: 2;
    }

    ul.dropdown .submenu {
      display: none;
      padding-left: 20px;
      position: absolute;
      top: 100%;
      left: 0;
      background-color: #76B39B;
      z-index: 2;
    }

    .sub .has-submenu:hover .submenu {
      display: block;
      animation: slideIn 2s ease-out;
    }

    h1 {
      margin-right: -30px;
    }

    .menu-icon {
      display: block;
      cursor: pointer;
      position: relative;
      z-index: 3;
      margin-left: -30px;
    }

    .menu-icon, .social {
      width: 50px;
      height: 50px;
    }

    ul.active {
      display: flex;
      flex-direction: column;
      margin-top: 0px;
      width: 100%;
      position: absolute;
      top: 120px;
      left: 0;
      background-color: #76B39B;
      z-index: 2;
    }

    .active_sub {
      display: flex;
      flex-direction: column;
      margin-top: 0px;
      position: absolute;
      left: 0;
      background-color: #345D4D;
      z-index: 2;
    }

    .social {
      font-size: 20px;
      margin: -10px;
    }

    #titre-principal {
      margin-right: 30px;
    }

    /* Ajout de l'animation slideIn */
    @keyframes slideIn {
      from {
        opacity: 0;
        transform: translateX(-10px);
      }
      to {
        opacity: 1;
        transform: translateX(0);
      }
    }
  }


</style>

<!-- Ajout du script JavaScript -->
<script>
  function toggleMenu() {
    var menu = document.querySelector('ul');
    menu.classList.toggle('active');

    var contenuPrincipal = document.querySelector('.contenu-principal');
    contenuPrincipal.classList.toggle('menu-open');   
    
    if (menu.classList.contains('active')) {
      contenuPrincipal.style.marginTop = '180px'; // Ajustez cette valeur selon votre design
    } else {
      contenuPrincipal.style.marginTop = '0';
    }
    }

  function toggleSubMenu(element) {
  var submenu = element.querySelector('.dropdown');
  var isOpen = submenu.classList.contains('active_sub');
  
  closeAllSubMenus(); // Fermer tous les sous-menus ouverts

  if (!isOpen) {
    submenu.classList.add('active_sub');
  }
}

  function closeAllSubMenus() {
  
  var subMenus = document.querySelectorAll('.dropdown');
  subMenus.forEach(function(submenu) {
    submenu.classList.remove('active_sub');
  });
}
</script>
<body>    
  <nav id="all-menu">    
    <div class="logo-container">
      <figure>
        <img src="{% static '/photos/logo_libeiki.png' %}" alt="Logo de votre site" class="logo">
      </figure>
      <div class="caption">
      <p id="nom"></p>
      </div>
    </div>  
    <div class="menu-container">
    <div class="title">
      <h1 id="titre-principal">LIBEIKI</h1>
    </div>  
    <!-- Bouton de menu pour les écrans plus petits -->
    <div class="menu-icon" id="menu-small" onclick="toggleMenu()">
    </div> 
    <ul class="dropdown-max menu-ul">
      <li class="menu-li"><a href="{% url 'libeiki:accueil' %}"><span class="fi-home"> ACCUEIL</span></a></li>
      <li class="sub menu-li" onclick="toggleSubMenu(this)">
        <a href="#">REIKI </a><span class="symbole">></span>
        <ul class="dropdown menu-ul">
          <li class="menu-li"><a href="{% url 'libeiki:reiki' %}">Qu'est ce que le Reiki?</a></li>
          <li class="menu-li"><a href="{% url 'libeiki:lignee_reiki' %}">Lignée Reiki</a></li>
          <li class="menu-li"><a href="{% url 'libeiki:reiki' %}#tarif-reiki">Tarifs</a></li>
        </ul>
      </li>
      <li class="sub menu-li" onclick="toggleSubMenu(this)">
        <a href="#">NUMEROLOGIE </a><span class="symbole">></span>
        <ul class="dropdown menu-ul">
          <li class="menu-li"><a href="{% url 'libeiki:numerologie' %}">Qu'est ce que la Numérologie?</a></li>
          <li class="menu-li"><a href="{% url 'libeiki:numerologie' %}#tarif-numerologie">Tarifs</a></li>
        </ul>
      </li>      
      <li class="menu-li sub" onclick="toggleSubMenu(this)">
        <a href="#">MASSAGE BAGUETTE KANSA </a><span class="symbole">></span>
        <ul class="dropdown menu-ul">
          <li class="menu-li"><a href="{% url 'libeiki:massage' %}">Qu'est ce que le Massage Baguette Kansa?</a></li>
          <li class="menu-li"><a href="{% url 'libeiki:massage' %}#tarif-massage">Tarifs</a></li>
        </ul>
      </li>
      <li class="sub menu-li" onclick="toggleSubMenu(this)">
        <a href="#">SOPHROLOGIE </a><span class="symbole">></span>
        <ul class="dropdown menu-ul">
          <li class="menu-li"><a href="{% url 'libeiki:sophrologie' %}">Qu'est ce que la Sophrologie?</a></li>
          <li class="menu-li"><a href="{% url 'libeiki:sophrologie' %}#tarif-sophrologie">Tarifs</a></li>
        </ul>
      </li>
      <li class="menu-li"><a href="{% url 'libeiki:contact' %}">CONTACT</a></li>
      <li class="menu-li"><a href="{% url 'libeiki:quisuisje' %}">QUI SUIS-JE ?</a></li>
      <li class="menu-li"><a href="{% url 'libeiki:send_commentaire' %}">LAISSER UN COMMENTAIRE</a></li>
    </ul>
  </div>
    <!-- Nouvelle structure pour les icônes sociales -->
    <div class="social-icons-container">
      <div class="social-text">JOAQUIM Gabrielle</div>
      <div class="social-text">07 64 37 51 26</div>
      <div class="social-icons">
        <a class="social" href="https://www.facebook.com/Libeiki" target="_blank">
          <i class="fi-social-facebook"></i> 
        </a>
        <a class="social" href="https://www.instagram.com/libeiki/" target="_blank">
          <i class="fi-social-instagram"></i>         
        </a>
        <a class="social" href="mailto:libellule_1982@hotmail.com" target="_blank"><i class="fi-mail"></i> </a>
      </div>
    </div>
  </nav>
</body>
{% endblock %}