ced091/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.main, name="main"),
    path('station/', include('station_meteo.urls')),
    path('libeiki/', include('libeiki.urls')),
    path('document/', include('docs.urls')),
    path('pokelira/', include('pokelira.urls')),
    path('sign-up/', views.signup, name="signup"),
    path('memo/', include('memo.urls')),
    path('admin/', admin.site.urls),
]

docs/urls.py
from django.urls import path, include
from . import views

app_name='docs'

urlpatterns = [
    path('documentation/<path:path>', views.main, name="main"),
]

libeiki/urls.py
from django.urls import path

from . import views

app_name = 'libeiki'

urlpatterns = [
    path('', views.accueil, name='accueil'),
    path('reiki/', views.reiki, name='reiki'),
    path('quisuisje/', views.quisuisje, name='quisuisje'),
    path('massage/', views.massage, name='massage'),
    path('sophrologie/', views.sophrologie, name='sophrologie'),
    path('numerologie/', views.numerologie, name='numerologie'),
    path('lignee-reiki/', views.lignee_reiki, name="lignee_reiki"),
    path('contact/', views.contact, name='contact'),
    path('tarif-reiki/', views.tarif_reiki, name='tarif_reiki'),
    path('tarif-numerologie/', views.tarif_numerologie, name='tarif_numerologie'),
    path('tarif-massage/', views.tarif_massage,name='tarif_massage'),
    path('tarif-sophrologie/', views.tarif_sophrologie,name='tarif_sophrologie'),
    path('send-commentaire/', views.send_commentaire, name='send_commentaire'),
    path('mentions-legales/', views.mentions_legales, name='mentions_legales'),
]

memo/urls.py
from django.urls import path

from . import views

app_name = 'memo'

urlpatterns = [
    path("", views.main, name="main"),
]

pokelira/urls.py
from django.urls import path

from . import views

app_name = 'pokelira'

urlpatterns = [
    path("", views.accueil, name="accueil"),
]

station_meteo/urls.py
from django.urls import path

from . import views
from . import ajax

app_name = 'station_meteo'

from .views import MeteoPointAPIView

urlpatterns = [
    path('', views.accueil, name='accueil'),
    path('refresh_data/', ajax.refresh_data, name="refresh_data"),
    path('api/save-meteo-point/', MeteoPointAPIView.as_view(), name='save_meteo_point'),

]

ced091/views.py
import logging

from django.shortcuts import render
from datetime import datetime

from django.utils import timezone

from datetime import datetime, timedelta

logger = logging.getLogger(__name__)

def log_user(request, vue):
    username = request.user.username if request.user.is_authenticated else 'Anonymous'
    current_datetime = timezone.now().strftime("%Y-%m-%d %H:%M:%S")
    ip_address = request.META.get('HTTP_X_FORWARDED_FOR', None)
    if ip_address is None:
        # Si l'en-tête X-Forwarded-For n'est pas disponible, utilisez l'adresse IP par défaut
        ip_address = request.META.get('REMOTE_ADDR', 'unknown')
    else:
        # Séparez les adresses IP si X-Forwarded-For contient plusieurs adresses
        ip_address = ip_address.split(",")[0].strip()
    logger.info(f'[{current_datetime}][{username}][{ip_address}] Accès à la vue {vue}')

def main(request):
    log_user(request, "main")
    date_now = datetime.now()
    affichage_date = date_now.strftime("%d-%m-%Y %H:%M:%S")
    context = {
        "date_nom": affichage_date
    }
    return render(request, "ced091/main_boot.html", context)

def signup(request):
    log_user(request, "signin")
    return render(request, "ced091/signup.html")

ced091/templates/ced091/base.html
{% load static i18n %}

<!DOCTYPE html>

<html>

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <link rel="stylesheet" href="/static/css/foundation.css">
  <link rel="stylesheet" href="/static/foundation-icons/foundation-icons/foundation-icons.css">
  <script src="/static/js/vendor/jquery.js" type="text/javascript"></script>
  <script src="/static/js/vendor/what-input.js"></script>
  <script src="/static/js/vendor/foundation.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
  <link rel="icon" href="{% static 'favicon.ico' %}">
  
</head>

<body>

{% block menu %}

{% endblock %}

{% block content %}
{% endblock %}

{% block script %}
  <script>
    $(document).foundation();
  </script>
{% endblock %}


</body>

</html>

ced091/templates/ced091/base_boot.html
{% load static i18n %}

<!DOCTYPE html>

<html>

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  <link rel="icon" href="{% static 'favicon.ico' %}">
  
</head>

<body>

{% block menu %}
{% endblock %}

{% block content %}
{% endblock %}

{% block script %}
{% endblock %}


</body>

</html>

ced091/templates/ced091/main.html
{% extends "ced091/base.html" %}

{% load static %}

{% block content %}

<style>
    .thumbnail {
        width: 50%;
    }
</style>
<div class="grid-container">

    
    <div class="grid-x">
        <div class="cell small-2 large-2">
            <img class="thumbnail" src="{% static 'favicon.ico' %}"  style="width: 70%">
        </div>
        <div class="cell small-10 large-10">
            <h1 style="text-align: left;">Bienvenue sur CED091</h1>
        </div>
    </div>
    <fieldset class="fieldset">
        <legend>Menu</legend>
            <p>
                <div class="grid-x">
                    <div class="cell small-4 large-3">
                        <a class="button secondary" href="{% url 'station_meteo:accueil' %}">Station Météo</a></p></br>
                    </div>
                    <div class="cell small-4 large-3">
                        <a class="button secondary" href="#">Pronostic</a></br>
                    </div>
                    <div class="cell small-4 large-3">
                        <a class="button secondary" href="{% url 'pokelira:accueil' %}">Pokélira</a>
                    </div>
                    <div class="cell small-4 large-3">
                        <a class="button secondary" href="{% url 'libeiki:accueil' %}">Site Gabrielle</a>
                    </div>
                    <div class="cell small-4 large-3">
                        <a class="button secondary" href="{% url 'docs:main' 'index.html' %}">Documentation</a>
                    </div>
                </div>
            </p>
    </fieldset>

    <img class="thumbnail" src="{% static '/photos/mathis_26_03_23.jpg' %}" alt="Mathis in the air">
    
</div>
{% endblock %}

ced091/templates/ced091/main_boot.html
{% extends "ced091/base_boot.html" %}
{% load static %}

{%block menu %}
    {% include "ced091/menu.html" %}
{% endblock %}

{% block content %}
<div class="container px-4 py-5" id="hanging-icons">
    <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
        <div class="col d-flex align-items-start">
            <div class="icon-square text-body-emphasis bg-body-secondary d-inline-flex align-items-center justify-content-center fs-4 flex-shrink-0 me-3">
                <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-thermometer-sun" viewBox="0 0 16 16">
                    <path d="M5 12.5a1.5 1.5 0 1 1-2-1.415V2.5a.5.5 0 0 1 1 0v8.585A1.5 1.5 0 0 1 5 12.5"/>
                    <path d="M1 2.5a2.5 2.5 0 0 1 5 0v7.55a3.5 3.5 0 1 1-5 0zM3.5 1A1.5 1.5 0 0 0 2 2.5v7.987l-.167.15a2.5 2.5 0 1 0 3.333 0L5 10.486V2.5A1.5 1.5 0 0 0 3.5 1m5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-1 0v-1a.5.5 0 0 1 .5-.5m4.243 1.757a.5.5 0 0 1 0 .707l-.707.708a.5.5 0 1 1-.708-.708l.708-.707a.5.5 0 0 1 .707 0M8 5.5a.5.5 0 0 1 .5-.5 3 3 0 1 1 0 6 .5.5 0 0 1 0-1 2 2 0 0 0 0-4 .5.5 0 0 1-.5-.5M12.5 8a.5.5 0 0 1 .5-.5h1a.5.5 0 1 1 0 1h-1a.5.5 0 0 1-.5-.5m-1.172 2.828a.5.5 0 0 1 .708 0l.707.708a.5.5 0 0 1-.707.707l-.708-.707a.5.5 0 0 1 0-.708M8.5 12a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-1 0v-1a.5.5 0 0 1 .5-.5"/>
                </svg>
            </div>
            <div>
                <h3 class="fs-2 text-body-emphasis">Station Météo</h3>
                <p>Capteur de pression, température, hygrométrie piloté par raspberrypi.</p>
                <a href="{% url 'station_meteo:accueil' %}" class="btn btn-primary">
                    Let's Go !
                </a>
            </div>
        </div>
        <div class="col d-flex align-items-start">
            <div class="icon-square text-body-emphasis bg-body-secondary d-inline-flex align-items-center justify-content-center fs-4 flex-shrink-0 me-3">
                <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50   " fill="currentColor" class="bi bi-dice-6" viewBox="0 0 16 16">
                    <path d="M13 1a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2zM3 0a3 3 0 0 0-3 3v10a3 3 0 0 0 3 3h10a3 3 0 0 0 3-3V3a3 3 0 0 0-3-3z"/>
                    <path d="M5.5 4a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0m8 0a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0m0 8a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0m0-4a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0m-8 4a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0m0-4a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0"/>
                </svg>
            </div>
            <div>
                <h3 class="fs-2 text-body-emphasis">Pronoced</h3>
                <p>Pronostic sportif sur le football ligue 1. Je connais déjà les scores.</p>
                <a href="#" class="btn btn-primary">
                    Let's Go !
                </a>
            </div>
        </div>
        <div class="col d-flex align-items-start">
            <div class="icon-square text-body-emphasis bg-body-secondary d-inline-flex align-items-center justify-content-center fs-4 flex-shrink-0 me-3">
                <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-file-earmark-text" viewBox="0 0 16 16">
                    <path d="M5.5 7a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1zM5 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5m0 2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5"/>
                    <path d="M9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.5zm0 1v2A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1z"/>
                </svg>
            </div>
            <div>
                <h3 class="fs-2 text-body-emphasis">Documentation</h3>
                <p>Documentation technique rédigée en resT à l'aide de la bibliothèque Sphinx.</p>
                <a href="{% url 'docs:main' 'index.html' %}" class="btn btn-primary">
                    Let's Go !
                </a>
            </div>
        </div>
    </div>
</div>
<div class="container px-4 py-5" id="hanging-icons">
    <h2 class="pb-2 border-bottom">En cours de dev. / Bac à sable</h2>
    <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
        <div class="col d-flex align-items-start">
            <div class="icon-square text-body-emphasis bg-body-secondary d-inline-flex align-items-center justify-content-center fs-4 flex-shrink-0 me-3">
                <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-dice-2" viewBox="0 0 16 16">
                    <path d="M13 1a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2zM3 0a3 3 0 0 0-3 3v10a3 3 0 0 0 3 3h10a3 3 0 0 0 3-3V3a3 3 0 0 0-3-3z"/>
                    <path d="M5.5 4a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0m8 8a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0"/>
                  </svg>
            </div>
            <div>
                <h3 class="fs-2 text-body-emphasis">Memo</h3>
                <p>Un jeu de mémo à 16 cartes pour application grid css</p>
                <a href="{% url 'memo:main' %}" class="btn btn-primary">
                    Let's Go !
                </a>
            </div>
        </div>       
    </div>
</div>

{% endblock %}

ced091/templates/ced091/menu.html
{% load static %}

{% block menu %}

<style>
.signup {
  color: black;
}
.icone {
  padding-right: 50px;
  padding-left: 50px;
}
</style>


    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
      <div class="col-md-3 mb-2 mb-md-0 icone">
        <a href="/" class="d-inline-flex link-body-emphasis text-decoration-none">
          <img class="thumbnail" src="{% static 'favicon.ico' %}"  style="width: 30%">
        </a>
      </div>

      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{% url 'main' %}" class="nav-link px-2 link-secondary">Home</a></li>
        <li><a href="{% url 'station_meteo:accueil' %}" class="nav-link px-2">Station Météo</a></li>
        <li><a href="#" class="nav-link px-2">Pronostic</a></li>
        <li><a href="{% url 'pokelira:accueil' %}" class="nav-link px-2">Pok Club Vid</a></li>
        <li><a href="{% url 'libeiki:accueil' %}" class="nav-link px-2">Site Gabrielle</a></li>
        <li><a href="{% url 'docs:main' 'index.html' %}" class="nav-link px-2">Documentation</a></li>
      </ul>

      <div class="col-md-3 text-end icone">
        <a class="btn btn-outline-primary me-2" href="#">Login</a>
        <a class="btn btn-primary" href="{% url 'signup' %}"><span class="signup">Sign-Up</span></a>
      </div>
    </header>

{% endblock %}

ced091/templates/ced091/signup.html
{% extends "ced091/base_boot.html" %}

{% load static %}

{% block menu %}

  {% include "ced091/menu.html" %}

{% endblock %}

{% block content %}
<style>
  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    user-select: none;
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
  }

  .b-example-divider {
    width: 100%;
    height: 3rem;
    background-color: rgba(0, 0, 0, .1);
    border: solid rgba(0, 0, 0, .15);
    border-width: 1px 0;
    box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
  }

  .b-example-vr {
    flex-shrink: 0;
    width: 1.5rem;
    height: 100vh;
  }

  .bi {
    vertical-align: -.125em;
    fill: currentColor;
  }

  .nav-scroller {
    position: relative;
    z-index: 2;
    height: 2.75rem;
    overflow-y: hidden;
  }

  .nav-scroller .nav {
    display: flex;
    flex-wrap: nowrap;
    padding-bottom: 1rem;
    margin-top: -1px;
    overflow-x: auto;
    text-align: center;
    white-space: nowrap;
    -webkit-overflow-scrolling: touch;
  }

  .btn-bd-primary {
    --bd-violet-bg: #712cf9;
    --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

    --bs-btn-font-weight: 600;
    --bs-btn-color: var(--bs-white);
    --bs-btn-bg: var(--bd-violet-bg);
    --bs-btn-border-color: var(--bd-violet-bg);
    --bs-btn-hover-color: var(--bs-white);
    --bs-btn-hover-bg: #6528e0;
    --bs-btn-hover-border-color: #6528e0;
    --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
    --bs-btn-active-color: var(--bs-btn-hover-color);
    --bs-btn-active-bg: #5a23c8;
    --bs-btn-active-border-color: #5a23c8;
  }

  .bd-mode-toggle {
    z-index: 1500;
  }

  .bd-mode-toggle .dropdown-menu .active .bi {
    display: block !important;
  }

.form-signin {
  max-width: 330px;
  padding: 1rem;
}

.form-signin .form-floating:focus-within {
  z-index: 2;
}

.form-signin input[type="email"] {
  margin-bottom: -1px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}

.form-signin input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}

main {
  margin-top: auto;
}
</style>  
<main class="form-signin w-100 m-auto">
<form>
  <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

  <div class="form-floating">
    <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
    <label for="floatingInput">Email address</label>
  </div>
  <div class="form-floating">
    <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
    <label for="floatingPassword">Password</label>
  </div>

  <div class="form-check text-start my-3">
    <input class="form-check-input" type="checkbox" value="remember-me" id="flexCheckDefault">
    <label class="form-check-label" for="flexCheckDefault">
      Remember me
    </label>
  </div>
  <button class="btn btn-primary w-100 py-2" type="submit">Sign in</button>
  <p class="mt-5 mb-3 text-body-secondary">&copy; prediced/ced091 2024</p>
</form>
</main>

{% endblock %}